### ISSUE TITLE
How can I start 3DRFPlayerConfigurator

### ISSUE THREAD

**Issue by WichtP** [ultrasuperpingu/3DRFPlayerConfigurator#1]
Hello, I'm beginner on smart home project. I'm very interessting for your configurator, I have a lot of problem to start the java configurator with my windows. I have downloaded your configurator but I don't understand how I can start your configurator. Can you help me please ? Best regards.

Pierre-Alain

**Comment by ultrasuperpingu** [comment]
Hello,
What's the problem? There is an executable ("3D RFPlayer Configurator.exe" for the windows version), you just have to start it and plug the device on a USB port.
Are-you using the Windows Build or the Linux one? The linux version is untested.

**Comment by WichtP** [comment]
Hello,

Thank you for your quick Answer. I had downloaded a zip file. If I understand I have to change the .zip to .exe ? Thank for your help. Best regards.

Pierre

**Comment by ultrasuperpingu** [comment]
No, you have to unzip the content of the zip file. A zip file is a compressed version of (possibly) multiple files. So, the zip archive contains multiple file and one of them is called "3D RFPlayer Configurator.exe". Just unzip the archive (Windows can do it, just double click on the zip file, it will open it as a directory and copy paste the content somewhere on your PC).

**Comment by WichtP** [comment]
Hello,

Thanks for your help, I downloaded the wrong file. I just find it now. I will test it tomorrow. Big Thank’s for your help Best regards

Pierre

**Comment by WichtP** [comment]
Hello ultrasuperpingu, Thank very match for your help. It's working now. Best regards. Pierre-Alain
