### ISSUE TITLE
Installation et exécution ?

### ISSUE THREAD

**Issue by Philtass** [ultrasuperpingu/3DRFPlayerConfigurator#3]
Bonjour. Je suis prêt à tester la version Linux, mais je ne suis pas développeur et je ne sais pas comment installer et exécuter ce programme sur mon système (Linux Kubuntu 22.04). Vous pouvez m'aider ?

**Comment by ultrasuperpingu** [comment]
Bonjour,
Normalement, il ne devrait pas y avoir trop de difficulté. Il faut juste dezippé l'archive, sans doute donner les droit d'exécution à l'exe (chmod +x 3DRFPlayerConfigurator.x86_64) et l'exécuter...
Si vous avez des erreurs en faisant ça, postez les ici, je verrais si je peux aider...

**Comment by Philtass** [comment]
Bonjour. Merci.Mais j'ai beau m’abîmer les yeux, je ne vois pas d'exécutable dans l'archive: 
![image](https://github.com/user-attachments/assets/085f14dc-3c44-492f-af4c-7be5da649b33)

**Comment by ultrasuperpingu** [comment]
Il s'agit de l'archive du code source :)
Je fournis une version compilée https://github.com/ultrasuperpingu/3DRFPlayerConfigurator/releases/tag/v0.4
Prenez bien 3DRFplayerConfigurator_Linux_v0.4.zip

**Comment by Philtass** [comment]
Ok, ça se lance, merci. J'ai une très belle animation du RFplayer et une demande de brancher le dongle sur USB... mais quand c'est fait, ça ne change rien. Je vais lire l'issue #1 "non détection du RFPlayer", et je reviens si je n'y arrive pas. Du coup je clos ce cas.
